export const SESSION_COOKIE = "hrn_session";

export const SYSTEM_ROLES = [
  "PLATFORM_ADMIN",
  "TENANT_OWNER",
  "TENANT_ADMIN",
  "HR_DIRECTOR",
  "HR_SPECIALIST",
  "PAYROLL_SPECIALIST",
  "FINANCE_MANAGER",
  "DEPARTMENT_MANAGER",
  "EMPLOYEE",
  "AUDITOR",
] as const;

export type SystemRole = (typeof SYSTEM_ROLES)[number];

export const ROLE_LABELS: Record<SystemRole, string> = {
  PLATFORM_ADMIN: "平台超级管理员",
  TENANT_OWNER: "企业所有者",
  TENANT_ADMIN: "企业管理员",
  HR_DIRECTOR: "HRD",
  HR_SPECIALIST: "HR 专员",
  PAYROLL_SPECIALIST: "薪酬专员",
  FINANCE_MANAGER: "财务负责人",
  DEPARTMENT_MANAGER: "部门负责人",
  EMPLOYEE: "普通员工",
  AUDITOR: "审计员",
};

export const PERMISSIONS = [
  "dashboard.view",
  "platform.view",
  "platform.manage_tenants",
  "platform.view_audit",
  "tenant.view",
  "tenant.manage",
  "users.view",
  "users.manage",
  "roles.view",
  "roles.manage",
  "permissions.view",
  "permissions.manage",
  "employees.view",
  "employees.create",
  "employees.update",
  "employees.delete",
  "employees.export",
  "employees.import",
  "employees.view_sensitive",
  "employees.manage_documents",
  "organization.view",
  "organization.manage",
  "organization.export",
  "departments.create",
  "departments.update",
  "departments.export",
  "positions.create",
  "positions.update",
  "positions.export",
  "cost_centers.create",
  "cost_centers.update",
  "cost_centers.export",
  "onboarding.view",
  "onboarding.manage",
  "onboarding.export",
  "lifecycle.view",
  "lifecycle.manage",
  "lifecycle.export",
  "contracts.view",
  "contracts.create",
  "contracts.update",
  "contracts.terminate",
  "contracts.renew",
  "contracts.export",
  "contracts.download_sensitive",
  "attendance.view",
  "attendance.manage",
  "attendance.export",
  "leave.view",
  "leave.apply",
  "leave.manage",
  "leave.approve",
  "leave.export",
  "payroll.view",
  "payroll.manage",
  "payroll.calculate",
  "payroll.approve",
  "payroll.publish",
  "payroll.export",
  "payroll.view_sensitive",
  "payslips.view_self",
  "payslips.view_all",
  "payslips.confirm",
  "social_security.view",
  "social_security.manage",
  "social_security.export",
  "workflows.view",
  "workflows.manage",
  "workflows.export",
  "approvals.view",
  "approvals.approve",
  "approvals.export",
  "recruitment.view",
  "recruitment.manage",
  "recruitment.export",
  "performance.view",
  "performance.manage",
  "performance.review",
  "performance.export",
  "training.view",
  "training.manage",
  "training.export",
  "analytics.view",
  "analytics.view_cost",
  "analytics.export",
  "notifications.view",
  "notifications.create",
  "notifications.manage",
  "notifications.export",
  "files.view",
  "files.upload",
  "files.download",
  "files.download_sensitive",
  "files.export",
  "settings.view",
  "settings.manage",
  "audit_logs.view",
  "audit_logs.export",
  "exports.view",
  "exports.manage",
  "ai.use",
  "ai.manage",
] as const;

export type PermissionCode = (typeof PERMISSIONS)[number];

const allTenantPermissions = PERMISSIONS.filter((permission) => !permission.startsWith("platform."));

export const ROLE_PERMISSIONS: Record<SystemRole, readonly PermissionCode[]> = {
  PLATFORM_ADMIN: [
    "dashboard.view",
    "platform.view",
    "platform.manage_tenants",
    "platform.view_audit",
  ],
  TENANT_OWNER: allTenantPermissions,
  TENANT_ADMIN: allTenantPermissions.filter(
    (permission) => !["payroll.view_sensitive", "payroll.publish"].includes(permission),
  ),
  HR_DIRECTOR: [
    "dashboard.view",
    "tenant.view",
    "users.view",
    "employees.view",
    "employees.create",
    "employees.update",
    "employees.export",
    "employees.import",
    "employees.view_sensitive",
    "employees.manage_documents",
    "organization.view",
    "organization.manage",
    "organization.export",
    "onboarding.view",
    "onboarding.manage",
    "onboarding.export",
    "lifecycle.view",
    "lifecycle.manage",
    "lifecycle.export",
    "contracts.view",
    "contracts.create",
    "contracts.update",
    "contracts.terminate",
    "contracts.renew",
    "contracts.export",
    "attendance.view",
    "attendance.manage",
    "attendance.export",
    "leave.view",
    "leave.manage",
    "leave.approve",
    "leave.export",
    "workflows.view",
    "workflows.export",
    "approvals.view",
    "approvals.approve",
    "approvals.export",
    "recruitment.view",
    "recruitment.manage",
    "recruitment.export",
    "performance.view",
    "performance.manage",
    "performance.export",
    "training.view",
    "training.manage",
    "training.export",
    "analytics.view",
    "analytics.export",
    "notifications.view",
    "notifications.export",
    "files.view",
    "files.upload",
    "files.download",
    "files.export",
  ],
  HR_SPECIALIST: [
    "dashboard.view",
    "employees.view",
    "employees.create",
    "employees.update",
    "employees.manage_documents",
    "organization.view",
    "onboarding.view",
    "onboarding.manage",
    "onboarding.export",
    "lifecycle.view",
    "lifecycle.manage",
    "contracts.view",
    "contracts.create",
    "contracts.update",
    "contracts.export",
    "attendance.view",
    "attendance.manage",
    "attendance.export",
    "leave.view",
    "leave.manage",
    "leave.export",
    "approvals.view",
    "recruitment.view",
    "recruitment.manage",
    "recruitment.export",
    "training.view",
    "notifications.view",
    "files.view",
    "files.upload",
    "files.download",
  ],
  PAYROLL_SPECIALIST: [
    "dashboard.view",
    "employees.view",
    "payroll.view",
    "payroll.manage",
    "payroll.calculate",
    "payroll.publish",
    "payroll.export",
    "payroll.view_sensitive",
    "payslips.view_all",
    "social_security.view",
    "social_security.manage",
    "social_security.export",
    "approvals.view",
    "notifications.view",
    "files.view",
  ],
  FINANCE_MANAGER: [
    "dashboard.view",
    "payroll.view",
    "payroll.approve",
    "payroll.export",
    "analytics.view",
    "analytics.view_cost",
    "analytics.export",
    "approvals.view",
    "approvals.approve",
    "notifications.view",
  ],
  DEPARTMENT_MANAGER: [
    "dashboard.view",
    "employees.view",
    "attendance.view",
    "leave.view",
    "leave.approve",
    "approvals.view",
    "approvals.approve",
    "performance.view",
    "performance.review",
    "training.view",
    "notifications.view",
  ],
  EMPLOYEE: [
    "dashboard.view",
    "tenant.view",
    "employees.view",
    "attendance.view",
    "leave.view",
    "leave.apply",
    "payslips.view_self",
    "payslips.confirm",
    "approvals.view",
    "performance.view",
    "training.view",
    "notifications.view",
    "files.view",
  ],
  AUDITOR: ["dashboard.view", "settings.view", "audit_logs.view", "audit_logs.export", "exports.view", "platform.view"],
};

export const SENSITIVE_FIELDS = [
  "idNumber",
  "phone",
  "bankAccount",
  "salary",
  "contractAttachment",
  "emergencyContactPhone",
  "address",
  "performanceComments",
  "terminationReason",
] as const;

export const DEMO_PASSWORD = "Demo123456!";
export const PLATFORM_ADMIN_PASSWORD = "Admin123456!";
